
language: python
python:
  - 3.8

cache: pip

install:
  - pip install --upgrade pip
  - pip install --upgrade -r requirements.txt
  - pip install --upgrade -r test_requirements.txt

script:
  - pytest
